export const GET_FAMOUSPERSONS = "GET_FAMOUSPERSONS";
export const ADD_FAMOUSPERSON = "ADD_FAMOUSPERSON";
export const SELECT_SINGLE_FAMOUSPERSON = "SELECT_SINGLE_FAMOUSPERSON";
export const DELETE_FAMOUSPERSON = "DELETE_FAMOUSPERSON";
export const EMPTY_SELECTED_FAMOUS_PERSON = "EMPTY_SELECTED_FAMOUS_PERSON";
export const UPDATE_FAMOUS_PERSON = "UPDATE_FAMOUS_PERSON";
